1-data-structures/2-javascript/1-array.MD
This PR is containing the detail explanation of DS Array in javascript
=> PR1: 1-array.MD

1-data-structures/1-java/3-queue
This is PR to the Java Queue Issue
=> pr: ava 3-queue

1-data-structures/0-c-programming/2-stack.MD
This PR contain Stack DS in C programming
=> PR2-stack.MD

1-data-structures/2-javascript/4-Linkedlist.MD
I have added explanation about linkedlist in JS
=> Added Linkedlist in JS

1-data-structures/0-c-programming/queue.MD
=> PR-queue-in-C-programming

1-data-structures/3-python/stack.MD
This PR contains the DS stack in Python
=> Stack in py

1-data-structures/3-python/Linkedlist in Python.md
Hey,
The issue #26 has been solved!!
You can merge it with the base repository!
Regards,
Gautam Bhagat.
=> LinkedList DS in python issue completed

1-data-structures/0-c-programming/linked-list.MD
This pull request contains a new Markdown document that explains the concept of Linked Lists in C Programming. It includes a definition, an explanation in simple terms, and code snippets to help readers understand the topic.
- Created a new Markdown file: `linked-list.MD`
- Added content about Linked Lists in C Programming.
- Included a clear and simple explanation for beginners.
- Provided code snippets to illustrate the concept.
- Ensured proper formatting and readability.
The purpose of this pull request is to contribute a beginner-friendly document about linked lists in C programming. It serves as an educational resource for those learning about data structures in C.
- Content accuracy and correctness.
- Clarity and simplicity of the explanation.
- Code snippets for accuracy and …
=> PR: DS Linked List in C programming

2-algorithms/1-java/merge sort in java.MD, 2-algorithms/1-java/merge-sort.MD
PR request for merge sort in java
=> PR:  Algo merge sort in java

2-algorithms/3-python/linear-search.md
closes issue #81 
please add `hacktoberfest-accepted` labels
=> PR Algo Linear Search in Python 

2-algorithms/2-javascript/linear search in javascript.MD, 2-algorithms/2-javascript/linear-search.MD
PR request for linear search in java script
=>  PR: Algo linear search in Javascript

2-algorithms/3-python/2-bubblesort.MD, 2-algorithms/3-python/bubble-sort.MD
This is a PR for bubble sort in python
=> PR:Algo Bubble Sort in Python

2-algorithms/3-python/2-selection-sort.MD, 2-algorithms/3-python/2-selectionsort.MD
This is a PR for  selection sort in python
=> PR:Algo Selection Sort in Python

2-algorithms/3-python/4-quicksort.MD
This is a PR for quick sort in python
=> PR:Algo Quick Sort in Python

2-algorithms/3-python/5-merge-sort.MD
Issue: #74 
algorithm added with explanation.
=> PR: Algo Merge sort in Python

2-algorithms/2-javascript/3-selection-sort.MD
I've added the Selection Sort algorithm using JavaScript. Along with the explanation I have also added the Time and Space complexity of the algorithm.
Fixes (#50)
=> PR: Algo Selection Sort in JavaScript

2-algorithms/0-c-programming/2-binary-search.MD
I have added explanation about binary search in c programming
=> PR: Algo binary-search in C programming

2-algorithms/2-javascript/2-Quick-sort.md
Issue: #59 issue solved and quick sort algo
This README provides an overview of Quick Sort, explains its operation in simple terms, and includes the JavaScript code for implementing the algorithm.
=> PR: Algo Quick Sort in JavaScript

2-algorithms/1-java/binary-search.MD
This pull request addresses the implementation of the binary search algorithm in Java.
Closes #102
=> PR: Algo binary search algorithm in Java

2-algorithms/1-java/shell-sort.md
This PR is about shell sort in java
=> PR: Algo Shell sort in java

2-algorithms/2-javascript/shell-sort.MD
In this pull request, I have implemented the Shell Sort algorithm in JavaScript as requested in issue #113 .
Closes #113
=> PR: Algo Shell Sort in JavaScript

2-algorithms/3-python/jump-search.MD
Added jump search algorithm in Python
Related to https://github.com/Abishethvarman/programming-resources/issues/130
=> Add jump search algorithm in python
